import axios, {type AxiosInstance} from "axios";
import MockAdapter from "axios-mock-adapter";

export const BASE_URL = import.meta.env.MODE === 'development'
    /*
    * local path
    * */
    ? 'http://localhost:3002'
    /*
    * 실서버
    * */
    : 'http://192.168.1.91:8080/';

export const api: AxiosInstance = axios.create({
  baseURL: BASE_URL
});

/*
* Axios mock 사용 여부
*
* development 환경에서만 mock 사용 (npm run dev)
*/
const USE_MOCK: boolean = import.meta.env.DEV;

if(USE_MOCK) {
  const mock = new MockAdapter(api, {delayResponse: 1000});

  /*
  * 칵테일 List
  * */
  mock.onGet('/api/cocktail').reply(200, {
    data: [
      {
        cocktailId: 1,
        isNew: true,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Mojito",
        cocktailNameKr: "모히토",
        category: "Refreshing",
        abs_percentage: 10,
        difficulty: 1,
        isVariation: false,
        profileNote: "상쾌한 민트와 라임의 조화가 완벽한 쿠바의 대표 칵테일",
        historyNote: "<p>모히토는 16세기 쿠바에서 시작된 칵테일로, 원래는 해적들이 마시던 음료였습니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>화이트 럼 60ml</li><li>신선한 민트 잎 10-12개</li><li>라임 1/2개</li><li>설탕 2티스푼</li><li>소다수</li><li>얼음</li></ul>",
        tip_note: "<p><strong>완벽한 모히토를 위한 팁:</strong></p><ul><li>민트 잎을 너무 세게 머들링하지 마세요</li></ul>",
        ingredients: {
          spirits: [{ id: 1, image: "https://images.unsplash.com/photo-1572441711009-31e2e5f64ba5?w=100&h=100&fit=crop", spiritName: "White Rum", spiritNameKr: "화이트 럼" }],
          juices: [{ id: 1, image: "https://images.unsplash.com/photo-1557401279-8e8de6c4659b?w=100&h=100&fit=crop", juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [{ id: 1, image: "https://images.unsplash.com/photo-1572441755997-6a0e8b3c1d42?w=100&h=100&fit=crop", syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [{ id: 1, image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=100&h=100&fit=crop", carbonatedName: "Soda Water", carbonatedNameKr: "소다수" }],
          dairy: [],
          garnishes: [{ id: 1, image: "https://images.unsplash.com/photo-1607103688605-8a06a4a4c4fc?w=100&h=100&fit=crop", garnishName: "Mint Leaves", garnishNameKr: "민트 잎" }],
          others: [{ id: 1, image: "https://images.unsplash.com/photo-1571167025672-ca4cb3cd8af1?w=100&h=100&fit=crop", otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=100&h=100&fit=crop", toolName: "Muddler", toolNameKr: "머들러" }],
        glassware: [{ id: 1, image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=100&h=100&fit=crop", glassName: "Highball Glass", glassNameKr: "하이볼 글라스" }],
        techniques: [{ id: 1, techniqueName: "Muddling", techniqueNameKr: "머들링" }],
        personalNotes: "처음 만들어본 칵테일이에요. 생각보다 간단해서 놀랐고, 민트향이 정말 상쾌했습니다!",
        MakerTips: "민트를 너무 세게 으깨면 정말 쓴맛이 나더라고요.",
        personalReview: "여름에 마시기 정말 좋은 칵테일이에요.",
        hashtags: { cocktailHashtagId: 1, cocktailHashtag: "모히토,쿠바,민트,상쾌한,여름칵테일,럼베이스,클래식" },
        likeCount: 127,
        shareCount: 45,
        comments: [],
        createAt: '2024-11-15',
        updatedAt: '2024-11-15'
      },
      {
        cocktailId: 2,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Margarita",
        cocktailNameKr: "마가리타",
        category: "Sour",
        abs_percentage: 15,
        difficulty: 2,
        isVariation: false,
        profileNote: "데킬라 베이스의 멕시코 전통 칵테일, 소금테 림이 특징",
        historyNote: "<p>마가리타는 1940년대 멕시코에서 탄생한 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>데킬라 60ml</li><li>라임 주스 30ml</li><li>트리플 섹 15ml</li><li>소금</li></ul>",
        tip_note: "<p><strong>완벽한 마가리타를 위한 팁:</strong></p><ul><li>글라스 림에 소금을 묻히는 것이 포인트입니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Tequila", spiritNameKr: "데킬라" }],
          juices: [{ id: 1, juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lime Wheel", garnishNameKr: "라임 휠" }],
          others: [{ id: 1, otherIngredientName: "Salt", otherIngredientNameKr: "소금" }, { id: 2, otherIngredientName: "Triple Sec", otherIngredientNameKr: "트리플 섹" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Margarita Glass", glassNameKr: "마가리타 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "멕시코 여행에서 마셔본 그 맛!",
        MakerTips: "소금 림을 만들 때 라임으로 글라스 가장자리를 적시면 소금이 잘 붙어요.",
        personalReview: "상큼하고 짭짤한 맛이 일품입니다.",
        hashtags: { cocktailHashtagId: 2, cocktailHashtag: "마가리타,데킬라,멕시코,소금림,상큼한" },
        likeCount: 89,
        shareCount: 32,
        comments: [],
        createAt: '2024-10-28',
        updatedAt: '2024-10-28'
      },
      {
        cocktailId: 3,
        image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&h=500&fit=crop",
        cocktailName: "Old Fashioned",
        cocktailNameKr: "올드 패션드",
        category: "Spirit Forward",
        abs_percentage: 35,
        difficulty: 3,
        isVariation: false,
        profileNote: "위스키의 깊은 맛을 느낄 수 있는 클래식한 칵테일",
        historyNote: "<p>올드 패션드는 1880년대 미국에서 탄생한 가장 오래된 칵테일 중 하나입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>버번 위스키 60ml</li><li>설탕 1티스푼</li><li>앙고스투라 비터스 2대시</li><li>오렌지 필</li></ul>",
        tip_note: "<p><strong>완벽한 올드 패션드를 위한 팁:</strong></p><ul><li>설탕을 완전히 녹이는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Bourbon Whiskey", spiritNameKr: "버번 위스키" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Angostura Bitters", bitterNameKr: "앙고스투라 비터스" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }],
        personalNotes: "위스키 애호가라면 반드시 마셔봐야 할 칵테일.",
        MakerTips: "오렌지 필을 짜서 향을 내는 것이 포인트예요.",
        personalReview: "진짜 어른의 맛이라고 할 수 있겠어요.",
        hashtags: { cocktailHashtagId: 3, cocktailHashtag: "올드패션드,위스키,클래식,버번,깊은맛" },
        likeCount: 203,
        shareCount: 67,
        comments: [],
        createAt: '2024-10-12',
        updatedAt: '2024-10-12'
      },
      {
        cocktailId: 4,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Negroni",
        cocktailNameKr: "네그로니",
        category: "Bitter",
        abs_percentage: 24,
        difficulty: 2,
        isVariation: false,
        profileNote: "진, 캄파리, 스위트 베르무트의 완벽한 조화",
        historyNote: "<p>네그로니는 1919년 이탈리아 플로렌스에서 탄생했습니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>진 30ml</li><li>캄파리 30ml</li><li>스위트 베르무트 30ml</li><li>오렌지 필</li></ul>",
        tip_note: "<p><strong>완벽한 네그로니를 위한 팁:</strong></p><ul><li>모든 재료를 1:1:1 비율로 맞추는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Gin", spiritNameKr: "진" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Campari", bitterNameKr: "캄파리" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sweet Vermouth", otherIngredientNameKr: "스위트 베르무트" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }],
        personalNotes: "처음엔 쓴맛이 강하다고 생각했는데 계속 마시니 중독적이에요.",
        MakerTips: "얼음을 크게 사용하면 희석이 적어져서 더 좋아요.",
        personalReview: "어른의 칵테일이라고 불리는 이유를 알겠어요.",
        hashtags: { cocktailHashtagId: 4, cocktailHashtag: "네그로니,진,캄파리,이탈리아,쓴맛,클래식" },
        likeCount: 156,
        shareCount: 43,
        comments: [],
        createAt: '2024-09-30',
        updatedAt: '2024-09-30'
      },
      {
        cocktailId: 5,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Whiskey Sour",
        cocktailNameKr: "위스키 사워",
        category: "Sour",
        abs_percentage: 20,
        difficulty: 2,
        isVariation: false,
        profileNote: "위스키의 강함과 레몬의 상큼함이 어우러진 칵테일",
        historyNote: "<p>위스키 사워는 1860년대 미국에서 탄생한 클래식 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>위스키 60ml</li><li>레몬 주스 30ml</li><li>심플 시럽 15ml</li><li>달걀 흰자 (선택)</li></ul>",
        tip_note: "<p><strong>완벽한 위스키 사워를 위한 팁:</strong></p><ul><li>달걀 흰자를 넣으면 부드러운 폼이 생깁니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Whiskey", spiritNameKr: "위스키" }],
          juices: [{ id: 1, juiceName: "Lemon Juice", juiceNameKr: "레몬 주스" }],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lemon Wheel", garnishNameKr: "레몬 휠" }],
          others: [{ id: 1, otherIngredientName: "Egg White", otherIngredientNameKr: "달걀 흰자" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Coupe Glass", glassNameKr: "쿠페 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "위스키를 잘 못 마시는데 이건 정말 맛있어요!",
        MakerTips: "달걀 흰자 없이도 충분히 맛있으니 부담갖지 마세요.",
        personalReview: "상큼하면서도 위스키 특유의 깊은 맛이 살아있어요.",
        hashtags: { cocktailHashtagId: 5, cocktailHashtag: "위스키사워,상큼한,레몬,클래식,사워계열" },
        likeCount: 74,
        shareCount: 28,
        comments: [],
        createAt: '2024-09-15',
        updatedAt: '2024-09-15'
      },
      {
        cocktailId: 6,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Espresso Martini",
        cocktailNameKr: "에스프레소 마티니",
        category: "Coffee",
        abs_percentage: 18.1,
        difficulty: 3,
        isVariation: false,
        profileNote: "커피의 깊은 맛과 보드카가 만나는 모던 클래식",
        historyNote: "<p>에스프레소 마티니는 1980년대 런던에서 탄생한 모던 클래식 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>보드카 50ml</li><li>커피 리큐어 20ml</li><li>에스프레소 1샷</li><li>심플 시럽 10ml</li></ul>",
        tip_note: "<p><strong>완벽한 에스프레소 마티니를 위한 팁:</strong></p><ul><li>갓 내린 에스프레소를 사용하는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Vodka", spiritNameKr: "보드카" }],
          juices: [],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Coffee Beans", garnishNameKr: "커피 원두" }],
          others: [{ id: 1, otherIngredientName: "Coffee Liqueur", otherIngredientNameKr: "커피 리큐어" }, { id: 2, otherIngredientName: "Espresso", otherIngredientNameKr: "에스프레소" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Martini Glass", glassNameKr: "마티니 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "커피 좋아하는 사람이라면 꼭 마셔봐야 해요!",
        MakerTips: "에스프레소가 뜨거우니 조심해서 셰이킹하세요.",
        personalReview: "달콤하면서도 쌉쌀한 커피 맛이 정말 좋아요.",
        hashtags: { cocktailHashtagId: 6, cocktailHashtag: "에스프레소마티니,커피,보드카,모던클래식,카페인" },
        likeCount: 92,
        shareCount: 35,
        comments: [],
        createAt: '2024-08-20',
        updatedAt: '2024-08-20'
      },
      {
        cocktailId: 1,
        isNew: true,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Mojito",
        cocktailNameKr: "모히토",
        category: "Refreshing",
        abs_percentage: 10,
        difficulty: 1,
        isVariation: false,
        profileNote: "상쾌한 민트와 라임의 조화가 완벽한 쿠바의 대표 칵테일",
        historyNote: "<p>모히토는 16세기 쿠바에서 시작된 칵테일로, 원래는 해적들이 마시던 음료였습니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>화이트 럼 60ml</li><li>신선한 민트 잎 10-12개</li><li>라임 1/2개</li><li>설탕 2티스푼</li><li>소다수</li><li>얼음</li></ul>",
        tip_note: "<p><strong>완벽한 모히토를 위한 팁:</strong></p><ul><li>민트 잎을 너무 세게 머들링하지 마세요</li></ul>",
        ingredients: {
          spirits: [{ id: 1, image: "https://images.unsplash.com/photo-1572441711009-31e2e5f64ba5?w=100&h=100&fit=crop", spiritName: "White Rum", spiritNameKr: "화이트 럼" }],
          juices: [{ id: 1, image: "https://images.unsplash.com/photo-1557401279-8e8de6c4659b?w=100&h=100&fit=crop", juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [{ id: 1, image: "https://images.unsplash.com/photo-1572441755997-6a0e8b3c1d42?w=100&h=100&fit=crop", syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [{ id: 1, image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=100&h=100&fit=crop", carbonatedName: "Soda Water", carbonatedNameKr: "소다수" }],
          dairy: [],
          garnishes: [{ id: 1, image: "https://images.unsplash.com/photo-1607103688605-8a06a4a4c4fc?w=100&h=100&fit=crop", garnishName: "Mint Leaves", garnishNameKr: "민트 잎" }],
          others: [{ id: 1, image: "https://images.unsplash.com/photo-1571167025672-ca4cb3cd8af1?w=100&h=100&fit=crop", otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=100&h=100&fit=crop", toolName: "Muddler", toolNameKr: "머들러" }],
        glassware: [{ id: 1, image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=100&h=100&fit=crop", glassName: "Highball Glass", glassNameKr: "하이볼 글라스" }],
        techniques: [{ id: 1, techniqueName: "Muddling", techniqueNameKr: "머들링" }],
        personalNotes: "처음 만들어본 칵테일이에요. 생각보다 간단해서 놀랐고, 민트향이 정말 상쾌했습니다!",
        MakerTips: "민트를 너무 세게 으깨면 정말 쓴맛이 나더라고요.",
        personalReview: "여름에 마시기 정말 좋은 칵테일이에요.",
        hashtags: { cocktailHashtagId: 1, cocktailHashtag: "모히토,쿠바,민트,상쾌한,여름칵테일,럼베이스,클래식" },
        likeCount: 127,
        shareCount: 45,
        comments: [],
        createAt: '2024-11-15',
        updatedAt: '2024-11-15'
      },
      {
        cocktailId: 2,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Margarita",
        cocktailNameKr: "마가리타",
        category: "Sour",
        abs_percentage: 15,
        difficulty: 2,
        isVariation: false,
        profileNote: "데킬라 베이스의 멕시코 전통 칵테일, 소금테 림이 특징",
        historyNote: "<p>마가리타는 1940년대 멕시코에서 탄생한 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>데킬라 60ml</li><li>라임 주스 30ml</li><li>트리플 섹 15ml</li><li>소금</li></ul>",
        tip_note: "<p><strong>완벽한 마가리타를 위한 팁:</strong></p><ul><li>글라스 림에 소금을 묻히는 것이 포인트입니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Tequila", spiritNameKr: "데킬라" }],
          juices: [{ id: 1, juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lime Wheel", garnishNameKr: "라임 휠" }],
          others: [{ id: 1, otherIngredientName: "Salt", otherIngredientNameKr: "소금" }, { id: 2, otherIngredientName: "Triple Sec", otherIngredientNameKr: "트리플 섹" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Margarita Glass", glassNameKr: "마가리타 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "멕시코 여행에서 마셔본 그 맛!",
        MakerTips: "소금 림을 만들 때 라임으로 글라스 가장자리를 적시면 소금이 잘 붙어요.",
        personalReview: "상큼하고 짭짤한 맛이 일품입니다.",
        hashtags: { cocktailHashtagId: 2, cocktailHashtag: "마가리타,데킬라,멕시코,소금림,상큼한" },
        likeCount: 89,
        shareCount: 32,
        comments: [],
        createAt: '2024-10-28',
        updatedAt: '2024-10-28'
      },
      {
        cocktailId: 3,
        image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&h=500&fit=crop",
        cocktailName: "Old Fashioned",
        cocktailNameKr: "올드 패션드",
        category: "Spirit Forward",
        abs_percentage: 35,
        difficulty: 3,
        isVariation: false,
        profileNote: "위스키의 깊은 맛을 느낄 수 있는 클래식한 칵테일",
        historyNote: "<p>올드 패션드는 1880년대 미국에서 탄생한 가장 오래된 칵테일 중 하나입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>버번 위스키 60ml</li><li>설탕 1티스푼</li><li>앙고스투라 비터스 2대시</li><li>오렌지 필</li></ul>",
        tip_note: "<p><strong>완벽한 올드 패션드를 위한 팁:</strong></p><ul><li>설탕을 완전히 녹이는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Bourbon Whiskey", spiritNameKr: "버번 위스키" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Angostura Bitters", bitterNameKr: "앙고스투라 비터스" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }],
        personalNotes: "위스키 애호가라면 반드시 마셔봐야 할 칵테일.",
        MakerTips: "오렌지 필을 짜서 향을 내는 것이 포인트예요.",
        personalReview: "진짜 어른의 맛이라고 할 수 있겠어요.",
        hashtags: { cocktailHashtagId: 3, cocktailHashtag: "올드패션드,위스키,클래식,버번,깊은맛" },
        likeCount: 203,
        shareCount: 67,
        comments: [],
        createAt: '2024-10-12',
        updatedAt: '2024-10-12'
      },
      {
        cocktailId: 4,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Negroni",
        cocktailNameKr: "네그로니",
        category: "Bitter",
        abs_percentage: 24,
        difficulty: 2,
        isVariation: false,
        profileNote: "진, 캄파리, 스위트 베르무트의 완벽한 조화",
        historyNote: "<p>네그로니는 1919년 이탈리아 플로렌스에서 탄생했습니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>진 30ml</li><li>캄파리 30ml</li><li>스위트 베르무트 30ml</li><li>오렌지 필</li></ul>",
        tip_note: "<p><strong>완벽한 네그로니를 위한 팁:</strong></p><ul><li>모든 재료를 1:1:1 비율로 맞추는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Gin", spiritNameKr: "진" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Campari", bitterNameKr: "캄파리" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sweet Vermouth", otherIngredientNameKr: "스위트 베르무트" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }],
        personalNotes: "처음엔 쓴맛이 강하다고 생각했는데 계속 마시니 중독적이에요.",
        MakerTips: "얼음을 크게 사용하면 희석이 적어져서 더 좋아요.",
        personalReview: "어른의 칵테일이라고 불리는 이유를 알겠어요.",
        hashtags: { cocktailHashtagId: 4, cocktailHashtag: "네그로니,진,캄파리,이탈리아,쓴맛,클래식" },
        likeCount: 156,
        shareCount: 43,
        comments: [],
        createAt: '2024-09-30',
        updatedAt: '2024-09-30'
      },
      {
        cocktailId: 5,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Whiskey Sour",
        cocktailNameKr: "위스키 사워",
        category: "Sour",
        abs_percentage: 20,
        difficulty: 2,
        isVariation: false,
        profileNote: "위스키의 강함과 레몬의 상큼함이 어우러진 칵테일",
        historyNote: "<p>위스키 사워는 1860년대 미국에서 탄생한 클래식 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>위스키 60ml</li><li>레몬 주스 30ml</li><li>심플 시럽 15ml</li><li>달걀 흰자 (선택)</li></ul>",
        tip_note: "<p><strong>완벽한 위스키 사워를 위한 팁:</strong></p><ul><li>달걀 흰자를 넣으면 부드러운 폼이 생깁니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Whiskey", spiritNameKr: "위스키" }],
          juices: [{ id: 1, juiceName: "Lemon Juice", juiceNameKr: "레몬 주스" }],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lemon Wheel", garnishNameKr: "레몬 휠" }],
          others: [{ id: 1, otherIngredientName: "Egg White", otherIngredientNameKr: "달걀 흰자" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Coupe Glass", glassNameKr: "쿠페 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "위스키를 잘 못 마시는데 이건 정말 맛있어요!",
        MakerTips: "달걀 흰자 없이도 충분히 맛있으니 부담갖지 마세요.",
        personalReview: "상큼하면서도 위스키 특유의 깊은 맛이 살아있어요.",
        hashtags: { cocktailHashtagId: 5, cocktailHashtag: "위스키사워,상큼한,레몬,클래식,사워계열" },
        likeCount: 74,
        shareCount: 28,
        comments: [],
        createAt: '2024-09-15',
        updatedAt: '2024-09-15'
      },
      {
        cocktailId: 6,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Espresso Martini",
        cocktailNameKr: "에스프레소 마티니",
        category: "Coffee",
        abs_percentage: 18.1,
        difficulty: 3,
        isVariation: false,
        profileNote: "커피의 깊은 맛과 보드카가 만나는 모던 클래식",
        historyNote: "<p>에스프레소 마티니는 1980년대 런던에서 탄생한 모던 클래식 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>보드카 50ml</li><li>커피 리큐어 20ml</li><li>에스프레소 1샷</li><li>심플 시럽 10ml</li></ul>",
        tip_note: "<p><strong>완벽한 에스프레소 마티니를 위한 팁:</strong></p><ul><li>갓 내린 에스프레소를 사용하는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Vodka", spiritNameKr: "보드카" }],
          juices: [],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Coffee Beans", garnishNameKr: "커피 원두" }],
          others: [{ id: 1, otherIngredientName: "Coffee Liqueur", otherIngredientNameKr: "커피 리큐어" }, { id: 2, otherIngredientName: "Espresso", otherIngredientNameKr: "에스프레소" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Martini Glass", glassNameKr: "마티니 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "커피 좋아하는 사람이라면 꼭 마셔봐야 해요!",
        MakerTips: "에스프레소가 뜨거우니 조심해서 셰이킹하세요.",
        personalReview: "달콤하면서도 쌉쌀한 커피 맛이 정말 좋아요.",
        hashtags: { cocktailHashtagId: 6, cocktailHashtag: "에스프레소마티니,커피,보드카,모던클래식,카페인" },
        likeCount: 92,
        shareCount: 35,
        comments: [],
        createAt: '2024-08-20',
        updatedAt: '2024-08-20'
      },
      {
        cocktailId: 1,
        isNew: true,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Mojito",
        cocktailNameKr: "모히토",
        category: "Refreshing",
        abs_percentage: 10,
        difficulty: 1,
        isVariation: false,
        profileNote: "상쾌한 민트와 라임의 조화가 완벽한 쿠바의 대표 칵테일",
        historyNote: "<p>모히토는 16세기 쿠바에서 시작된 칵테일로, 원래는 해적들이 마시던 음료였습니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>화이트 럼 60ml</li><li>신선한 민트 잎 10-12개</li><li>라임 1/2개</li><li>설탕 2티스푼</li><li>소다수</li><li>얼음</li></ul>",
        tip_note: "<p><strong>완벽한 모히토를 위한 팁:</strong></p><ul><li>민트 잎을 너무 세게 머들링하지 마세요</li></ul>",
        ingredients: {
          spirits: [{ id: 1, image: "https://images.unsplash.com/photo-1572441711009-31e2e5f64ba5?w=100&h=100&fit=crop", spiritName: "White Rum", spiritNameKr: "화이트 럼" }],
          juices: [{ id: 1, image: "https://images.unsplash.com/photo-1557401279-8e8de6c4659b?w=100&h=100&fit=crop", juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [{ id: 1, image: "https://images.unsplash.com/photo-1572441755997-6a0e8b3c1d42?w=100&h=100&fit=crop", syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [{ id: 1, image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=100&h=100&fit=crop", carbonatedName: "Soda Water", carbonatedNameKr: "소다수" }],
          dairy: [],
          garnishes: [{ id: 1, image: "https://images.unsplash.com/photo-1607103688605-8a06a4a4c4fc?w=100&h=100&fit=crop", garnishName: "Mint Leaves", garnishNameKr: "민트 잎" }],
          others: [{ id: 1, image: "https://images.unsplash.com/photo-1571167025672-ca4cb3cd8af1?w=100&h=100&fit=crop", otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=100&h=100&fit=crop", toolName: "Muddler", toolNameKr: "머들러" }],
        glassware: [{ id: 1, image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=100&h=100&fit=crop", glassName: "Highball Glass", glassNameKr: "하이볼 글라스" }],
        techniques: [{ id: 1, techniqueName: "Muddling", techniqueNameKr: "머들링" }],
        personalNotes: "처음 만들어본 칵테일이에요. 생각보다 간단해서 놀랐고, 민트향이 정말 상쾌했습니다!",
        MakerTips: "민트를 너무 세게 으깨면 정말 쓴맛이 나더라고요.",
        personalReview: "여름에 마시기 정말 좋은 칵테일이에요.",
        hashtags: { cocktailHashtagId: 1, cocktailHashtag: "모히토,쿠바,민트,상쾌한,여름칵테일,럼베이스,클래식" },
        likeCount: 127,
        shareCount: 45,
        comments: [],
        createAt: '2024-11-15',
        updatedAt: '2024-11-15'
      },
      {
        cocktailId: 2,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Margarita",
        cocktailNameKr: "마가리타",
        category: "Sour",
        abs_percentage: 15,
        difficulty: 2,
        isVariation: false,
        profileNote: "데킬라 베이스의 멕시코 전통 칵테일, 소금테 림이 특징",
        historyNote: "<p>마가리타는 1940년대 멕시코에서 탄생한 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>데킬라 60ml</li><li>라임 주스 30ml</li><li>트리플 섹 15ml</li><li>소금</li></ul>",
        tip_note: "<p><strong>완벽한 마가리타를 위한 팁:</strong></p><ul><li>글라스 림에 소금을 묻히는 것이 포인트입니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Tequila", spiritNameKr: "데킬라" }],
          juices: [{ id: 1, juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lime Wheel", garnishNameKr: "라임 휠" }],
          others: [{ id: 1, otherIngredientName: "Salt", otherIngredientNameKr: "소금" }, { id: 2, otherIngredientName: "Triple Sec", otherIngredientNameKr: "트리플 섹" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Margarita Glass", glassNameKr: "마가리타 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "멕시코 여행에서 마셔본 그 맛!",
        MakerTips: "소금 림을 만들 때 라임으로 글라스 가장자리를 적시면 소금이 잘 붙어요.",
        personalReview: "상큼하고 짭짤한 맛이 일품입니다.",
        hashtags: { cocktailHashtagId: 2, cocktailHashtag: "마가리타,데킬라,멕시코,소금림,상큼한" },
        likeCount: 89,
        shareCount: 32,
        comments: [],
        createAt: '2024-10-28',
        updatedAt: '2024-10-28'
      },
      {
        cocktailId: 3,
        image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&h=500&fit=crop",
        cocktailName: "Old Fashioned",
        cocktailNameKr: "올드 패션드",
        category: "Spirit Forward",
        abs_percentage: 35,
        difficulty: 3,
        isVariation: false,
        profileNote: "위스키의 깊은 맛을 느낄 수 있는 클래식한 칵테일",
        historyNote: "<p>올드 패션드는 1880년대 미국에서 탄생한 가장 오래된 칵테일 중 하나입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>버번 위스키 60ml</li><li>설탕 1티스푼</li><li>앙고스투라 비터스 2대시</li><li>오렌지 필</li></ul>",
        tip_note: "<p><strong>완벽한 올드 패션드를 위한 팁:</strong></p><ul><li>설탕을 완전히 녹이는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Bourbon Whiskey", spiritNameKr: "버번 위스키" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Angostura Bitters", bitterNameKr: "앙고스투라 비터스" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }],
        personalNotes: "위스키 애호가라면 반드시 마셔봐야 할 칵테일.",
        MakerTips: "오렌지 필을 짜서 향을 내는 것이 포인트예요.",
        personalReview: "진짜 어른의 맛이라고 할 수 있겠어요.",
        hashtags: { cocktailHashtagId: 3, cocktailHashtag: "올드패션드,위스키,클래식,버번,깊은맛" },
        likeCount: 203,
        shareCount: 67,
        comments: [],
        createAt: '2024-10-12',
        updatedAt: '2024-10-12'
      },
      {
        cocktailId: 4,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Negroni",
        cocktailNameKr: "네그로니",
        category: "Bitter",
        abs_percentage: 24,
        difficulty: 2,
        isVariation: false,
        profileNote: "진, 캄파리, 스위트 베르무트의 완벽한 조화",
        historyNote: "<p>네그로니는 1919년 이탈리아 플로렌스에서 탄생했습니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>진 30ml</li><li>캄파리 30ml</li><li>스위트 베르무트 30ml</li><li>오렌지 필</li></ul>",
        tip_note: "<p><strong>완벽한 네그로니를 위한 팁:</strong></p><ul><li>모든 재료를 1:1:1 비율로 맞추는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Gin", spiritNameKr: "진" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Campari", bitterNameKr: "캄파리" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sweet Vermouth", otherIngredientNameKr: "스위트 베르무트" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }],
        personalNotes: "처음엔 쓴맛이 강하다고 생각했는데 계속 마시니 중독적이에요.",
        MakerTips: "얼음을 크게 사용하면 희석이 적어져서 더 좋아요.",
        personalReview: "어른의 칵테일이라고 불리는 이유를 알겠어요.",
        hashtags: { cocktailHashtagId: 4, cocktailHashtag: "네그로니,진,캄파리,이탈리아,쓴맛,클래식" },
        likeCount: 156,
        shareCount: 43,
        comments: [],
        createAt: '2024-09-30',
        updatedAt: '2024-09-30'
      },
      {
        cocktailId: 5,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Whiskey Sour",
        cocktailNameKr: "위스키 사워",
        category: "Sour",
        abs_percentage: 20,
        difficulty: 2,
        isVariation: false,
        profileNote: "위스키의 강함과 레몬의 상큼함이 어우러진 칵테일",
        historyNote: "<p>위스키 사워는 1860년대 미국에서 탄생한 클래식 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>위스키 60ml</li><li>레몬 주스 30ml</li><li>심플 시럽 15ml</li><li>달걀 흰자 (선택)</li></ul>",
        tip_note: "<p><strong>완벽한 위스키 사워를 위한 팁:</strong></p><ul><li>달걀 흰자를 넣으면 부드러운 폼이 생깁니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Whiskey", spiritNameKr: "위스키" }],
          juices: [{ id: 1, juiceName: "Lemon Juice", juiceNameKr: "레몬 주스" }],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lemon Wheel", garnishNameKr: "레몬 휠" }],
          others: [{ id: 1, otherIngredientName: "Egg White", otherIngredientNameKr: "달걀 흰자" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Coupe Glass", glassNameKr: "쿠페 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "위스키를 잘 못 마시는데 이건 정말 맛있어요!",
        MakerTips: "달걀 흰자 없이도 충분히 맛있으니 부담갖지 마세요.",
        personalReview: "상큼하면서도 위스키 특유의 깊은 맛이 살아있어요.",
        hashtags: { cocktailHashtagId: 5, cocktailHashtag: "위스키사워,상큼한,레몬,클래식,사워계열" },
        likeCount: 74,
        shareCount: 28,
        comments: [],
        createAt: '2024-09-15',
        updatedAt: '2024-09-15'
      },
      {
        cocktailId: 6,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Espresso Martini",
        cocktailNameKr: "에스프레소 마티니",
        category: "Coffee",
        abs_percentage: 18.1,
        difficulty: 3,
        isVariation: false,
        profileNote: "커피의 깊은 맛과 보드카가 만나는 모던 클래식",
        historyNote: "<p>에스프레소 마티니는 1980년대 런던에서 탄생한 모던 클래식 칵테일입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>보드카 50ml</li><li>커피 리큐어 20ml</li><li>에스프레소 1샷</li><li>심플 시럽 10ml</li></ul>",
        tip_note: "<p><strong>완벽한 에스프레소 마티니를 위한 팁:</strong></p><ul><li>갓 내린 에스프레소를 사용하는 것이 중요합니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Vodka", spiritNameKr: "보드카" }],
          juices: [],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Coffee Beans", garnishNameKr: "커피 원두" }],
          others: [{ id: 1, otherIngredientName: "Coffee Liqueur", otherIngredientNameKr: "커피 리큐어" }, { id: 2, otherIngredientName: "Espresso", otherIngredientNameKr: "에스프레소" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }],
        glassware: [{ id: 1, glassName: "Martini Glass", glassNameKr: "마티니 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "커피 좋아하는 사람이라면 꼭 마셔봐야 해요!",
        MakerTips: "에스프레소가 뜨거우니 조심해서 셰이킹하세요.",
        personalReview: "달콤하면서도 쌉쌀한 커피 맛이 정말 좋아요.",
        hashtags: { cocktailHashtagId: 6, cocktailHashtag: "에스프레소마티니,커피,보드카,모던클래식,카페인" },
        likeCount: 92,
        shareCount: 35,
        comments: [],
        createAt: '2024-08-20',
        updatedAt: '2024-08-20'
      }
    ]
  });

  /*
  * 칵테일 Detail (개별 조회)
  * */
  mock.onGet(/\/api\/cocktail\/\d+/).reply((config) => {
    const cocktailId = parseInt(config.url?.split('/').pop() || '1');
    
    // 칵테일 데이터 맵
    const cocktailDataMap: { [key: number]: any } = {
      1: {
        cocktailId: 1,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Mojito",
        cocktailNameKr: "모히토",
        category: "Refreshing",
        abs_percentage: 10,
        difficulty: 1,
        isVariation: false,
        profileNote: "상쾌한 민트와 라임의 조화가 완벽한 쿠바의 대표 칵테일",
        historyNote: "<p>모히토는 16세기 쿠바에서 시작된 칵테일로, 원래는 해적들이 마시던 음료였습니다.</p><p>현재의 형태는 20세기 초 하바나의 바에서 완성되었으며, 어니스트 헤밍웨이가 사랑했던 칵테일로도 유명합니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>화이트 럼 60ml</li><li>신선한 민트 잎 10-12개</li><li>라임 1/2개</li><li>설탕 2티스푼</li><li>소다수</li><li>얼음</li></ul><p><strong>만드는 법:</strong></p><ol><li>하이볼 글라스에 민트 잎과 설탕을 넣고 가볍게 머들링</li><li>라임 조각을 추가하고 다시 머들링</li><li>럼을 넣고 얼음으로 채움</li><li>소다수로 탑업하고 가볍게 저어줌</li></ol>",
        tip_note: "<p><strong>완벽한 모히토를 위한 팁:</strong></p><ul><li>민트 잎을 너무 세게 머들링하지 마세요</li><li>신선한 라임 주스를 사용하세요</li><li>소다수는 마지막에 넣어 탄산이 빠지지 않도록 하세요</li><li>얼음은 큼직한 것을 사용하면 희석을 줄일 수 있습니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, image: "https://images.unsplash.com/photo-1572441711009-31e2e5f64ba5?w=100&h=100&fit=crop", spiritName: "White Rum", spiritNameKr: "화이트 럼" }],
          juices: [{ id: 1, image: "https://images.unsplash.com/photo-1557401279-8e8de6c4659b?w=100&h=100&fit=crop", juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [{ id: 1, image: "https://images.unsplash.com/photo-1572441755997-6a0e8b3c1d42?w=100&h=100&fit=crop", syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [{ id: 1, image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=100&h=100&fit=crop", carbonatedName: "Soda Water", carbonatedNameKr: "소다수" }],
          dairy: [],
          garnishes: [{ id: 1, image: "https://images.unsplash.com/photo-1607103688605-8a06a4a4c4fc?w=100&h=100&fit=crop", garnishName: "Mint Leaves", garnishNameKr: "민트 잎" }, { id: 2, garnishName: "Lime Wedge", garnishNameKr: "라임 웨지" }],
          others: [{ id: 1, image: "https://images.unsplash.com/photo-1571167025672-ca4cb3cd8af1?w=100&h=100&fit=crop", otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=100&h=100&fit=crop", toolName: "Muddler", toolNameKr: "머들러" }, { id: 2, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=100&h=100&fit=crop", glassName: "Highball Glass", glassNameKr: "하이볼 글라스" }],
        techniques: [{ id: 1, techniqueName: "Muddling", techniqueNameKr: "머들링" }, { id: 2, techniqueName: "Building", techniqueNameKr: "빌드" }],
        personalNotes: "처음 만들어본 칵테일이에요. 생각보다 간단해서 놀랐고, 민트향이 정말 상쾌했습니다!",
        MakerTips: "민트를 너무 세게 으깨면 정말 쓴맛이 나더라고요.",
        personalReview: "여름에 마시기 정말 좋은 칵테일이에요.",
        hashtags: { cocktailHashtagId: 1, cocktailHashtag: "모히토,쿠바,민트,상쾌한,여름칵테일,럼베이스,클래식" },
        likeCount: 127,
        shareCount: 45,
        comments: [
          { id: 1, username: "칵테일러버", content: "정말 맛있는 레시피네요! 민트의 양을 조절하는 게 포인트인 것 같아요.", createdDate: "2024-11-10", replies: [{ id: 1, username: "작성자", content: "맞아요! 민트는 개인 취향에 따라 조절하시면 됩니다.", createdDate: "2024-11-10" }] }
        ],
        createAt: '2024-11-15',
        updatedAt: '2024-11-15'
      },
      2: {
        cocktailId: 2,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Margarita",
        cocktailNameKr: "마가리타",
        category: "Sour",
        abs_percentage: 15,
        difficulty: 2,
        isVariation: false,
        profileNote: "데킬라 베이스의 멕시코 전통 칵테일, 소금테 림이 특징",
        historyNote: "<p>마가리타는 1940년대 멕시코에서 탄생한 칵테일입니다.</p><p>여러 기원설이 있지만, 가장 유명한 것은 티후아나의 바텐더 카를로스 헤레라가 만들었다는 설입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>데킬라 60ml</li><li>라임 주스 30ml</li><li>트리플 섹 15ml</li><li>소금</li></ul><p><strong>만드는 법:</strong></p><ol><li>글라스 림에 소금을 묻힘</li><li>모든 재료를 셰이커에 넣고 얼음과 함께 셰이킹</li><li>스트레인하여 글라스에 따름</li></ol>",
        tip_note: "<p><strong>완벽한 마가리타를 위한 팁:</strong></p><ul><li>글라스 림에 소금을 묻히는 것이 포인트입니다</li><li>신선한 라임 주스를 사용하세요</li><li>데킬라는 100% 아가베를 사용한 것이 좋습니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Tequila", spiritNameKr: "데킬라" }],
          juices: [{ id: 1, juiceName: "Lime Juice", juiceNameKr: "라임 주스" }],
          bitters: [],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lime Wheel", garnishNameKr: "라임 휠" }],
          others: [{ id: 1, otherIngredientName: "Salt", otherIngredientNameKr: "소금" }, { id: 2, otherIngredientName: "Triple Sec", otherIngredientNameKr: "트리플 섹" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }, { id: 2, toolName: "Strainer", toolNameKr: "스트레이너" }],
        glassware: [{ id: 1, glassName: "Margarita Glass", glassNameKr: "마가리타 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "멕시코 여행에서 마셔본 그 맛!",
        MakerTips: "소금 림을 만들 때 라임으로 글라스 가장자리를 적시면 소금이 잘 붙어요.",
        personalReview: "상큼하고 짭짤한 맛이 일품입니다.",
        hashtags: { cocktailHashtagId: 2, cocktailHashtag: "마가리타,데킬라,멕시코,소금림,상큼한" },
        likeCount: 89,
        shareCount: 32,
        comments: [],
        createAt: '2024-10-28',
        updatedAt: '2024-10-28'
      },
      3: {
        cocktailId: 3,
        image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&h=500&fit=crop",
        cocktailName: "Old Fashioned",
        cocktailNameKr: "올드 패션드",
        category: "Spirit Forward",
        abs_percentage: 35,
        difficulty: 3,
        isVariation: false,
        profileNote: "위스키의 깊은 맛을 느낄 수 있는 클래식한 칵테일",
        historyNote: "<p>올드 패션드는 1880년대 미국에서 탄생한 가장 오래된 칵테일 중 하나입니다.</p><p>'옛날식으로 만들어달라'는 요청에서 이름이 유래되었으며, 칵테일의 원형으로 여겨집니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>버번 위스키 60ml</li><li>설탕 1티스푼</li><li>앙고스투라 비터스 2대시</li><li>오렌지 필</li></ul><p><strong>만드는 법:</strong></p><ol><li>글라스에 설탕과 비터스를 넣고 으깸</li><li>위스키를 넣고 얼음과 함께 저어줌</li><li>오렌지 필로 가니시</li></ol>",
        tip_note: "<p><strong>완벽한 올드 패션드를 위한 팁:</strong></p><ul><li>설탕을 완전히 녹이는 것이 중요합니다</li><li>오렌지 필을 짜서 향을 내세요</li><li>큰 얼음을 사용하면 희석을 줄일 수 있습니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Bourbon Whiskey", spiritNameKr: "버번 위스키" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Angostura Bitters", bitterNameKr: "앙고스투라 비터스" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sugar", otherIngredientNameKr: "설탕" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }, { id: 2, toolName: "Muddler", toolNameKr: "머들러" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }, { id: 2, techniqueName: "Muddling", techniqueNameKr: "머들링" }],
        personalNotes: "위스키 애호가라면 반드시 마셔봐야 할 칵테일.",
        MakerTips: "오렌지 필을 짜서 향을 내는 것이 포인트예요.",
        personalReview: "진짜 어른의 맛이라고 할 수 있겠어요.",
        hashtags: { cocktailHashtagId: 3, cocktailHashtag: "올드패션드,위스키,클래식,버번,깊은맛" },
        likeCount: 203,
        shareCount: 67,
        comments: [],
        createAt: '2024-10-12',
        updatedAt: '2024-10-12'
      },
      4: {
        cocktailId: 4,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Negroni",
        cocktailNameKr: "네그로니",
        category: "Bitter",
        abs_percentage: 24,
        difficulty: 2,
        isVariation: false,
        profileNote: "진, 캄파리, 스위트 베르무트의 완벽한 조화",
        historyNote: "<p>네그로니는 1919년 이탈리아 플로렌스에서 탄생했습니다.</p><p>카밀로 네그로니 백작이 아메리카노 칵테일에서 소다수 대신 진을 넣어달라고 요청한 것이 시초입니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>진 30ml</li><li>캄파리 30ml</li><li>스위트 베르무트 30ml</li><li>오렌지 필</li></ul><p><strong>만드는 법:</strong></p><ol><li>모든 재료를 글라스에 넣음</li><li>얼음과 함께 저어줌</li><li>오렌지 필로 가니시</li></ol>",
        tip_note: "<p><strong>완벽한 네그로니를 위한 팁:</strong></p><ul><li>모든 재료를 1:1:1 비율로 맞추는 것이 중요합니다</li><li>좋은 진과 베르무트를 사용하세요</li><li>얼음은 큰 것을 사용하면 좋습니다</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Gin", spiritNameKr: "진" }],
          juices: [],
          bitters: [{ id: 1, bitterName: "Campari", bitterNameKr: "캄파리" }],
          syrups: [],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Orange Peel", garnishNameKr: "오렌지 필" }],
          others: [{ id: 1, otherIngredientName: "Sweet Vermouth", otherIngredientNameKr: "스위트 베르무트" }]
        },
        tools: [{ id: 1, toolName: "Bar Spoon", toolNameKr: "바 스푼" }],
        glassware: [{ id: 1, glassName: "Old Fashioned Glass", glassNameKr: "올드 패션드 글라스" }],
        techniques: [{ id: 1, techniqueName: "Stirring", techniqueNameKr: "스터링" }],
        personalNotes: "처음엔 쓴맛이 강하다고 생각했는데 계속 마시니 중독적이에요.",
        MakerTips: "얼음을 크게 사용하면 희석이 적어져서 더 좋아요.",
        personalReview: "어른의 칵테일이라고 불리는 이유를 알겠어요.",
        hashtags: { cocktailHashtagId: 4, cocktailHashtag: "네그로니,진,캄파리,이탈리아,쓴맛,클래식" },
        likeCount: 156,
        shareCount: 43,
        comments: [],
        createAt: '2024-09-30',
        updatedAt: '2024-09-30'
      },
      5: {
        cocktailId: 5,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Whiskey Sour",
        cocktailNameKr: "위스키 사워",
        category: "Sour",
        abs_percentage: 20,
        difficulty: 2,
        isVariation: false,
        profileNote: "위스키의 강함과 레몬의 상큼함이 어우러진 칵테일",
        historyNote: "<p>위스키 사워는 1860년대 미국에서 탄생한 클래식 칵테일입니다.</p><p>골드러시 시대 선원들이 괴혈병 예방을 위해 레몬 주스를 위스키에 넣어 마신 것이 시초라고 합니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>위스키 60ml</li><li>레몬 주스 30ml</li><li>심플 시럽 15ml</li><li>달걀 흰자 (선택)</li></ul><p><strong>만드는 법:</strong></p><ol><li>모든 재료를 셰이커에 넣고 드라이 셰이킹</li><li>얼음을 넣고 다시 셰이킹</li><li>스트레인하여 글라스에 따름</li></ol>",
        tip_note: "<p><strong>완벽한 위스키 사워를 위한 팁:</strong></p><ul><li>달걀 흰자를 넣으면 부드러운 폼이 생깁니다</li><li>드라이 셰이킹 후 얼음 셰이킹을 하세요</li><li>신선한 레몬 주스를 사용하세요</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Whiskey", spiritNameKr: "위스키" }],
          juices: [{ id: 1, juiceName: "Lemon Juice", juiceNameKr: "레몬 주스" }],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Lemon Wheel", garnishNameKr: "레몬 휠" }, { id: 2, garnishName: "Cherry", garnishNameKr: "체리" }],
          others: [{ id: 1, otherIngredientName: "Egg White", otherIngredientNameKr: "달걀 흰자" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }, { id: 2, toolName: "Strainer", toolNameKr: "스트레이너" }],
        glassware: [{ id: 1, glassName: "Coupe Glass", glassNameKr: "쿠페 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }],
        personalNotes: "위스키를 잘 못 마시는데 이건 정말 맛있어요!",
        MakerTips: "달걀 흰자 없이도 충분히 맛있으니 부담갖지 마세요.",
        personalReview: "상큼하면서도 위스키 특유의 깊은 맛이 살아있어요.",
        hashtags: { cocktailHashtagId: 5, cocktailHashtag: "위스키사워,상큼한,레몬,클래식,사워계열" },
        likeCount: 74,
        shareCount: 28,
        comments: [],
        createAt: '2024-09-15',
        updatedAt: '2024-09-15'
      },
      6: {
        cocktailId: 6,
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=500&fit=crop",
        cocktailName: "Espresso Martini",
        cocktailNameKr: "에스프레소 마티니",
        category: "Coffee",
        abs_percentage: 18.1,
        difficulty: 3,
        isVariation: false,
        profileNote: "커피의 깊은 맛과 보드카가 만나는 모던 클래식",
        historyNote: "<p>에스프레소 마티니는 1980년대 런던에서 탄생한 모던 클래식 칵테일입니다.</p><p>바텐더 딕 브래드셀이 한 모델의 '나를 깨워주고 취하게 해줄 칵테일'이라는 요청으로 만들어졌습니다.</p>",
        note: "<p><strong>재료:</strong></p><ul><li>보드카 50ml</li><li>커피 리큐어 20ml</li><li>에스프레소 1샷</li><li>심플 시럽 10ml</li></ul><p><strong>만드는 법:</strong></p><ol><li>모든 재료를 셰이커에 넣음</li><li>얼음과 함께 강하게 셰이킹</li><li>더블 스트레인하여 마티니 글라스에 따름</li><li>커피 원두 3개로 가니시</li></ol>",
        tip_note: "<p><strong>완벽한 에스프레소 마티니를 위한 팁:</strong></p><ul><li>갓 내린 에스프레소를 사용하는 것이 중요합니다</li><li>강하게 셰이킹해야 위에 크레마가 생깁니다</li><li>더블 스트레인을 해서 찌꺼기를 걸러주세요</li></ul>",
        ingredients: {
          spirits: [{ id: 1, spiritName: "Vodka", spiritNameKr: "보드카" }],
          juices: [],
          bitters: [],
          syrups: [{ id: 1, syrupName: "Simple Syrup", syrupNameKr: "심플 시럽" }],
          carbonated: [],
          dairy: [],
          garnishes: [{ id: 1, garnishName: "Coffee Beans", garnishNameKr: "커피 원두" }],
          others: [{ id: 1, otherIngredientName: "Coffee Liqueur", otherIngredientNameKr: "커피 리큐어" }, { id: 2, otherIngredientName: "Espresso", otherIngredientNameKr: "에스프레소" }]
        },
        tools: [{ id: 1, toolName: "Shaker", toolNameKr: "셰이커" }, { id: 2, toolName: "Fine Strainer", toolNameKr: "파인 스트레이너" }],
        glassware: [{ id: 1, glassName: "Martini Glass", glassNameKr: "마티니 글라스" }],
        techniques: [{ id: 1, techniqueName: "Shaking", techniqueNameKr: "셰이킹" }, { id: 2, techniqueName: "Double Straining", techniqueNameKr: "더블 스트레이닝" }],
        personalNotes: "커피 좋아하는 사람이라면 꼭 마셔봐야 해요!",
        MakerTips: "에스프레소가 뜨거우니 조심해서 셰이킹하세요.",
        personalReview: "달콤하면서도 쌉쌀한 커피 맛이 정말 좋아요.",
        hashtags: { cocktailHashtagId: 6, cocktailHashtag: "에스프레소마티니,커피,보드카,모던클래식,카페인" },
        likeCount: 92,
        shareCount: 35,
        comments: [],
        createAt: '2024-08-20',
        updatedAt: '2024-08-20'
      }
    };

    const cocktailData = cocktailDataMap[cocktailId];

    if (!cocktailData) {
      return [404, { error: 'Cocktail not found' }];
    }

    return [200, { data: cocktailData }];
  });
}